# CC3001 2022-2 - Tarea 4: Matrices poco densas -- Leonardo Rikhardsson


## Profesores: Nelson Baloian, Jérémy Barbay, Benjamín Bustos, Patricio Poblete

Según las condiciones de su sección, pueden entregar un link a su tarea en `colab` o subir un archivo en el formato Jupyter NoteBook (`.ipynb`). Puede crear todas las funciones auxiliares que requiera para implementar las funciones solicitadas. Para programar las funciones debe usar los *array* de *numpy*. Los únicos métodos de los objetos de tipo *array* que puede utilizar en su solución son los siguientes:

- El método *array* para crear un arreglo.
- Los métodos *zeros*, *ones* y *full* para inicializar un *array*.

No se puede utilizar ningún otro método disponible en módulos de Python.

# El Problema

Una matriz se define como "poco densa" cuando tiene pocos valores distintos de cero. En este caso, si se crea un arreglo de dos dimensiones para almacenar la matriz poco densa, se gastaría mucho espacio en memoria para guardar todos los valores en cero. Una forma alternativa para representar estas matrices poco densas que permite ahorrar memoria es la siguiente:

- Suponga que la matriz poco densa es de tamaño $n \times n$ y que se utiliza para guardar valores enteros positivos.
- Se utiliza un arreglo de tamaño $n$ que almacena cada una de las filas de la matriz poco densa. Las filas en el arreglo están ordenadas por número de fila, es decir, en el índice $0$ del arreglo se almacena la primera fila de la matriz, en el índice $1$ del arreglo se almacena la segunda fila de la matriz, etc.
- Cada casillero del arreglo almacena una referencia a una lista que contiene objetos con dos atributos: *columna*, que indica la columna correspondiente de la matriz, y *valor*, que contiene el valor almacenado en dicho casillero. La lista sólo contiene nodos para aquellos casilleros cuyo valor almacenado es distinto de cero.

Con esta representación, el uso de memoria es proporcional al número de valores distintos de cero de la matriz poco densa.

Considere la siguiente definición para los nodos de una lista:

In [ ]:
class Info:
    def __init__(self, columna, valor):
        self.columna = columna
        self.valor = valor

class Nodo:
    def __init__(self, info, sgte=None):
        self.info = info # objeto de la clase Info
        self.sgte = sgte

# Parte 1

Implemente la función *imprime*, que devuelve un String con los valores de la matriz (incluidos los casilleros con valor 0). Por ejemplo, si la matriz contiene los valores:

$$\begin{bmatrix} 0 & 0 & 1 \\ 20 & 0 & 1 \\ 7 & 0 & 0 \end{bmatrix}$$

la función *imprime* devuelve un String que al mostrarlo en la pantalla con *print* produce lo siguiente:

[0 0 1]<br>
[20 0 1]<br>
[7 0 0]

Es decir, en el String devuelto cada fila comienza con '[' y termina con ']', los valores se separan con un espacio en blanco, y cada fila termina con el caracter '\n'.

In [ ]:
# Solución

import numpy

def imprime(matriz):
  # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
  n=len(matriz)
  string = ""
  #Para comenzar cada array
  for fila in matriz:
    string += "["
    for size in range(0,n):
      if fila is None:
        #En el caso de que 0 sea el ultimo valor
        if size == n-1:
          string += "0"
        #En el caso de que 0 no sea el ultimo valor
        else:
          string += "0 "
      elif fila is not None:
        #En el caso de que el valor sea el ultimo valor
        if size == n-1:
          string += str(fila.info.valor)
          fila = fila.sgte
        #En el caso de que el valor no sea el ultimo valor
        elif fila.info.columna == size:
          string += str(fila.info.valor) + " "
          fila = fila.sgte
        else:
          #En el caso de que el valor sea 0
          if size == n-1:
            string += "0"
          else:
            string += "0 "
    #Para terminar el array
    string += "]\n"
  return string

  # Algunos tests que le pueden servir para probar su codigo
# matriz de 5 x 5
fila0 = Nodo(Info(1, 42), Nodo(Info(3, 17), None))
fila1 = Nodo(Info(2, 35), Nodo(Info(3, 12), None))
fila2 = Nodo(Info(0, 1), Nodo(Info(4, 20), None))
fila3 = None
fila4 = Nodo(Info(1, 4), Nodo(Info(2, 8), Nodo(Info(4, 50), None)))
matriz = numpy.array([fila0, fila1, fila2, fila3, fila4])
texto = imprime(matriz)
assert texto == '[0 42 0 17 0]\n[0 0 35 12 0]\n[1 0 0 0 20]\n[0 0 0 0 0]\n[0 4 8 0 50]\n'
print('Su codigo paso todos los tests!')
print()
print(texto)

Su codigo paso todos los tests!

[0 42 0 17 0]
[0 0 35 12 0]
[1 0 0 0 20]
[0 0 0 0 0]
[0 4 8 0 50]



# Parte 2

Implemente la función *valor*, que devuelve el valor almacenado en el casillero $[i,j]$ de la matriz poco densa. Note que si el valor del casillero es 0 no se encuentra almacenado en la estructura de datos, pero la función en este caso debe devolver el 0. La función recibe una referencia a la matriz, y dos enteros con los índices de la fila y columna (valores entre $0$ y $n-1$ si la matriz es de tamaño $n \times n$).

In [ ]:
# Solución

import numpy

def valor(matriz, fila, columna):
    # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
    if matriz[fila] is None:
      return 0
    else:
      testo = matriz[fila]
      while testo is not None:
        if testo.info.columna == columna:
          num = testo.info.valor
          return num
        testo = testo.sgte
    #caso en que ninguna condicion anterior se cumpla
    return 0

# Algunos tests que le pueden servir para probar su codigo
# matriz de 5 x 5
fila0 = Nodo(Info(1, 42), Nodo(Info(3, 17), None))
fila1 = Nodo(Info(2, 35), Nodo(Info(3, 12), None))
fila2 = Nodo(Info(0, 1), Nodo(Info(4, 20), None))
fila3 = None
fila4 = Nodo(Info(1, 4), Nodo(Info(2, 8), Nodo(Info(4, 50), None)))
matriz = numpy.array([fila0, fila1, fila2, fila3, fila4])
assert valor(matriz, 2, 4) == 20
assert valor(matriz, 3, 3) == 0
assert valor(matriz, 0, 1) == 42
assert valor(matriz, 4, 2) == 8
assert valor(matriz, 4, 3) == 0
print('Su codigo paso todos los tests!')
#print(matriz[1].info.columna)

Su codigo paso todos los tests!


# Parte 3

Implemente la función *asignar*, que permite asignar un valor al casillero $[i,j]$ de la matriz poco densa. Note que si el valor asignado es 0, se debe borrar dicho nodo de la lista correspondiente (si es que existe). La función recibe una referencia a la matriz, dos enteros con los índices de la fila y columna (valores entre $0$ y $n-1$ si la matriz es de tamaño $n \times n$), y el valor a asignar al casillero.

In [ ]:
def asignar(matriz, fila, columna, valor):
    # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
    n = len(matriz)
    testo = matriz[fila]
    if matriz[fila] is None:
      if valor == 0:
        return
      else:
        matriz[fila] = Nodo(Info(columna,valor),None)
        return
    else:
      while matriz[fila] is not None:
        if testo.info.columna == columna:
          testo.info.valor = valor
          return
        elif testo.sgte is None:
          testo.sgte = Nodo(Info(columna,valor),None)
          return
        else:
          testo = testo.sgte


# Algunos tests que le pueden servir para probar su codigo
# matriz de 5 x 5
matriz = numpy.array([None, None, None, None, None])
asignar(matriz, 0, 1, 42)
asignar(matriz, 0, 3, 17)
asignar(matriz, 1, 2, 35)
asignar(matriz, 1, 3, 12)
asignar(matriz, 2, 0, 1)
asignar(matriz, 2, 4, 20)
asignar(matriz, 4, 1, 4)
asignar(matriz, 4, 2, 8)
asignar(matriz, 4, 4, 50)
assert valor(matriz, 2, 4) == 20
print(imprime(matriz))
assert valor(matriz, 3, 3) == 0
assert valor(matriz, 0, 1) == 42
assert valor(matriz, 4, 2) == 8
assert valor(matriz, 4, 3) == 0
asignar(matriz, 4, 4, 0)
print(imprime(matriz))
assert valor(matriz, 4, 4) == 0
print('Su codigo paso todos los tests!')

[0 42 0 17 0]
[0 0 35 12 0]
[1 0 0 0 20]
[0 0 0 0 0]
[0 4 8 0 50]

[0 42 0 17 0]
[0 0 35 12 0]
[1 0 0 0 20]
[0 0 0 0 0]
[0 4 8 0 0]

Su codigo paso todos los tests!


# Parte 4

Implemente la función *sumar*, que devuelve la matriz resultante de sumar dos matrices poco densas. La matriz resultante también se representa como matriz poco densa. Ambas matrices deben tener las mismas dimensiones para que la operación se pueda realizar. La función recibe como parámetro las referencias a las dos matrices.

In [ ]:
# Solución

import numpy

def sumar(matriz1, matriz2):
    # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
    n = len(matriz1)
    #Creamos una matriz nula para ir rellenandola con las sumas correspondientes
    m = [None for z in range(n)]
    for x in range(0,n):
      for y in range(0,n):
        asignar(m, x, y, valor(matriz1, x, y) + valor(matriz2, x, y))
    return m


# Algunos tests que le pueden servir para probar su codigo
# matrices de 5 x 5
matriz1 = numpy.array([None, None, None, None, None])
asignar(matriz1, 0, 1, 42)
asignar(matriz1, 0, 3, 17)
asignar(matriz1, 1, 2, 35)
asignar(matriz1, 1, 3, 12)
asignar(matriz1, 2, 0, 1)
asignar(matriz1, 2, 4, 20)
asignar(matriz1, 4, 1, 4)
asignar(matriz1, 4, 2, 8)
asignar(matriz1, 4, 4, 50)
matriz2 = numpy.array([None, None, None, None, None])
asignar(matriz2, 0, 1, 1)
asignar(matriz2, 0, 3, 1)
asignar(matriz2, 1, 2, 1)
asignar(matriz2, 1, 3, 1)
asignar(matriz2, 2, 0, 1)
asignar(matriz2, 2, 4, 1)
asignar(matriz2, 4, 1, 1)
asignar(matriz2, 4, 2, 1)
asignar(matriz2, 4, 4, 1)
matriz = sumar(matriz1, matriz2)
print(imprime(matriz1))
print(imprime(matriz2))
print(imprime(matriz))
assert valor(matriz, 2, 4) == 21
assert valor(matriz, 3, 3) == 0
assert valor(matriz, 0, 1) == 43
assert valor(matriz, 4, 2) == 9
assert valor(matriz, 4, 3) == 0
print('Su codigo paso todos los tests!')

[0 42 0 17 0]
[0 0 35 12 0]
[1 0 0 0 20]
[0 0 0 0 0]
[0 4 8 0 50]

[0 1 0 1 0]
[0 0 1 1 0]
[1 0 0 0 1]
[0 0 0 0 0]
[0 1 1 0 1]

[0 43 0 18 0]
[0 0 36 13 0]
[2 0 0 0 21]
[0 0 0 0 0]
[0 5 9 0 51]

Su codigo paso todos los tests!


# Parte 5

Implemente la función *multiplicar*, que devuelve la matriz resultante de multiplicar dos matrices poco densas. La matriz resultante también se representa como matriz poco densa. Ambas matrices deben tener las mismas dimensiones para que la operación se pueda realizar. La función recibe como parámetro las referencias a las dos matrices.

In [ ]:
# Solución

import numpy

def multiplicar(matriz1, matriz2):
    # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
    n = len(matriz1)
    l = len(matriz2)
    #Creamos una matriz nula
    m = [None for largo in range(n)]
    for x in range(0,n):
      for y in range(0,n):
        C = 0
        for z in range(0,l):
          A = valor(matriz1, x, z)
          B = valor(matriz2, z, y)
          C += A*B
          asignar(m, x, y, C)
    return m


# Algunos tests que le pueden servir para probar su codigo
# matrices de 5 x 5
matriz1 = numpy.array([None, None, None, None, None])
asignar(matriz1, 0, 1, 42)
asignar(matriz1, 0, 3, 17)
asignar(matriz1, 1, 2, 35)
asignar(matriz1, 1, 3, 12)
asignar(matriz1, 2, 0, 1)
asignar(matriz1, 2, 4, 20)
asignar(matriz1, 4, 1, 4)
asignar(matriz1, 4, 2, 8)
asignar(matriz1, 4, 4, 50)
matriz2 = numpy.array([None, None, None, None, None])
asignar(matriz2, 0, 0, 1)
asignar(matriz2, 1, 1, 1)
asignar(matriz2, 2, 2, 1)
asignar(matriz2, 3, 3, 1)
asignar(matriz2, 4, 4, 1)
matriz = multiplicar(matriz1, matriz2)
print(imprime(matriz1))
print(imprime(matriz2))
print(imprime(matriz))
assert valor(matriz, 2, 4) == 20
assert valor(matriz, 3, 3) == 0
assert valor(matriz, 0, 1) == 42
assert valor(matriz, 4, 2) == 8
assert valor(matriz, 4, 3) == 0
print('Su codigo paso todos los tests!')

[0 42 0 17 0]
[0 0 35 12 0]
[1 0 0 0 20]
[0 0 0 0 0]
[0 4 8 0 50]

[1 0 0 0 0]
[0 1 0 0 0]
[0 0 1 0 0]
[0 0 0 1 0]
[0 0 0 0 1]

[0 42 0 17 0]
[0 0 35 12 0]
[1 0 0 0 20]
[0 0 0 0 0]
[0 4 8 0 50]

Su codigo paso todos los tests!
