# CC3001 2022-2 - Tarea 3: Programación Dinámica -- Leonardo Rikhardsson


## Profesores: Nelson Baloian, Jérémy Barbay, Benjamín Bustos, Patricio Poblete

Según las condiciones de su sección, pueden entregar un link a su tarea en `colab` o subir un archivo en el formato Jupyter NoteBook (`.ipynb`). Puede crear todas las funciones auxiliares que requiera para implementar las funciones solicitadas. Para programar las funciones debe usar los *array* de *numpy*. Los únicos métodos de los objetos de tipo *array* que puede utilizar en su solución son los siguientes:

- El método *array* para crear un arreglo.
- Los métodos *zeros*, *ones* y *full* para inicializar un *array*.

No se puede utilizar ningún otro método disponible en módulos de Python.

# El Problema

Suponga que se tienen dos series de valores $A$ y $B$, representadas como arreglos, Por ejemplo:


In [ ]:
import math
import numpy

A = numpy.array([1, 1, 3, 5, 2])
B = numpy.array([1, 2, 2, 5, 1])

El problema a resolver es medir cuánto se parecen las series de valores. Si las series tienen el mismo largo, como en el ejemplo, una forma de medir su parecido es calculando la distancia Euclidiana entre ambas series:

In [ ]:
def distanciaEuclidiana(serie1, serie2):
    assert len(serie1) == len(serie2)
    resultado = 0
    for i in range(len(serie1)):
        resultado += (serie1[i] - serie2[i]) ** 2
    return math.sqrt(resultado)

print(distanciaEuclidiana(A, B))

1.7320508075688772


En el caso que el largo de las series de valores no sean iguales, no es posible calcular la distancia Euclidiana. Para resolver esto, se propone la siguiente fórmula recursiva para calcular la distancia entre las dos series de valores:

- Sea una serie de valores $A$ de largo $i$ (denominada $A_i$) y una serie de valores $B$ de largo $j$ (denominada $B_j$).
- Si las dos series de valores tienen largo cero, su distancia es 0.
- Si una de las series de valores tiene largo 0, y la otra tiene largo estrictamente mayor que cero, su distancia es "infinito" (esto se puede representar con el valor *numpy.inf*)
- Si no, la distancia entre las series $A_i$ y $B_j$ se define recursivamente como:

$$ distancia(A_i, B_j) = costo(A_i, B_j) + \min\{ distancia(A_{i-1}, B_{j}),  distancia(A_{i}, B_{j-1}), distancia(A_{i-1}, B_{j-1})\} $$

La función $costo(A_i, B_j)$ devuelve un número que corresponde al cuadrado de la diferencia entre el $i$-ésimo valor de la serie $A$ y el $j$-ésimo valor de la serie $B$. *Nota*: Usted no debe editar la función de costo.

In [ ]:
# costo: num num -> num
def costo(x, y):
    return (x - y) ** 2

# Parte 1

Implemente usando recursión el cálculo de la distancia entre dos series de valores.

In [ ]:
# Solución

import numpy

def distanciaRecursiva(A, B):

  return distanciaRecursivaAux(A,B,len(A),len(B))

def distanciaRecursivaAux(A, B, i, j):
    # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
    if i == 0 and j == 0:
      return 0
    elif (i == 0 and j > 0) or (j == 0 and i > 0):
      return numpy.inf
    else:
      return costo(A[i-1], B[j-1]) + min(distanciaRecursivaAux(A, B, i-1, j),distanciaRecursivaAux(A, B, i, j-1),distanciaRecursivaAux(A, B, i-1, j-1))

# Algunos tests que le pueden servir para probar su codigo
A = numpy.array([1, 1, 2, 3, 2, 0])
B = numpy.array([0, 1, 1, 2, 3, 2, 1])
assert distanciaRecursiva(A, B) == 2
A = numpy.array([1, 2, 3, 3, 4, 1])
B = numpy.array([1, 1, 3, 4, 3, 1])
assert distanciaRecursiva(A, B) == 2
A = numpy.array([3, 1, 2, 2, 1])
B = numpy.array([2, 0, 0, 3, 3, 1, 0])
assert distanciaRecursiva(A, B) == 6
A = numpy.array([1, 4, 5, 10, 9, 3, 2, 6, 8, 4])
B = numpy.array([1, 7, 3, 4, 1, 10, 5, 4, 7, 4])
assert distanciaRecursiva(A, B) == 37
print('Su codigo paso todos los tests!')

Su codigo paso todos los tests!


# Parte 2

Implemente usando la técnica de memoización el cálculo de la distancia entre dos series de valores, de forma de evitar que se repitan llamados recursivos. Puede usar como base su código implementado para la Parte 1.

In [ ]:
# Solución

import numpy

def distanciaMemoizacion(A, B):
    # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
    i=len(A)
    j=len(B)
    memo = numpy.zeros((i+1,j+1),dtype=float)
    def distanciaMemoizacionAux(A, B, i, j):
      # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
      if i == 0 and j == 0:
        memo[i,j] = 0
      if (i == 0 and j > 0) or (j == 0 and i > 0):
        memo[i,j] = numpy.inf
      if i > 0 and j > 0 and memo[i,j] == 0:
        memo[i,j] = costo(A[i-1], B[j-1]) + min(distanciaMemoizacionAux(A, B, i-1, j),distanciaMemoizacionAux(A, B, i, j-1),distanciaMemoizacionAux(A, B, i-1, j-1))
      return memo[i,j]
    return distanciaMemoizacionAux(A, B, i, j)

# Algunos tests que le pueden servir para probar su codigo
A = numpy.array([1, 1, 2, 3, 2, 0])
B = numpy.array([0, 1, 1, 2, 3, 2, 1])
assert distanciaMemoizacion(A, B) == 2
A = numpy.array([1, 2, 3, 3, 4, 1])
B = numpy.array([1, 1, 3, 4, 3, 1])
assert distanciaMemoizacion(A, B) == 2
A = numpy.array([3, 1, 2, 2, 1])
B = numpy.array([2, 0, 0, 3, 3, 1, 0])
assert distanciaMemoizacion(A, B) == 6
A = numpy.array([1, 4, 5, 10, 9, 3, 2, 6, 8, 4])
B = numpy.array([1, 7, 3, 4, 1, 10, 5, 4, 7, 4])
assert distanciaMemoizacion(A, B) == 37
print('Su codigo paso todos los tests!')

Su codigo paso todos los tests!


# Parte 3

Implemente utilizando tabulación (Programación Dinámica) el cálculo de la distancia entre dos series de valores. Para esto, defina una matriz $C$ en donde vaya guardando los resultados a los subproblemas. *Sugerencia*: Inicialice la primera fila y la primera columna de la matriz $C$, y luego piense en cómo ir rellenando el resto de la matriz con los valores previamente calculados.

In [ ]:
# Solución

import numpy

def distanciaProgramacionDinamica(A, B):
    # Escriba aqui su codigo, puede crear funciones auxiliares si lo requiere
    m = len(A)
    n = len(B)
    D=numpy.zeros((m+1,n+1),dtype=float)
    D[0,0] = 0 #Aunque no es necesario colocar D[0,0] = 0 como ya de por si
               # me entrega 0 cuando ambas matrices son de largo 0
    for i in range(1,m+1):
      D[i,0] = numpy.inf #Caso cuando la matriz B es de largo 0
    for j in range(1,n+1):
      D[0,j] = numpy.inf #Caso cuando la matriz A es de largo 0
    for i in range(1,m+1):
      for j in range(1,n+1):
          D[i,j] = costo(A[i-1],B[j-1]) + min(D[i-1,j],D[i,j-1],D[i-1,j-1])
    return D[m,n]

# Algunos tests que le pueden servir para probar su codigo
A = numpy.array([1, 1, 2, 3, 2, 0])
B = numpy.array([0, 1, 1, 2, 3, 2, 1])
assert distanciaProgramacionDinamica(A, B) == 2
A = numpy.array([1, 2, 3, 3, 4, 1])
B = numpy.array([1, 1, 3, 4, 3, 1])
assert distanciaProgramacionDinamica(A, B) == 2
A = numpy.array([3, 1, 2, 2, 1])
B = numpy.array([2, 0, 0, 3, 3, 1, 0])
assert distanciaProgramacionDinamica(A, B) == 6
A = numpy.array([1,4,5,10,9,3,2,6,8,4])
B = numpy.array([1,7,3,4,1,10,5,4,7,4])
assert distanciaProgramacionDinamica(A, B) == 37
A = numpy.array([1,4,5,10,9,3,2,6,8,4,1,4,5,10,9,3,2,6,8,4])
B = numpy.array([1,7,3,4,1,10,5,4,7,4,1,7,3,4,1,10,5,4,7,4])
assert distanciaProgramacionDinamica(A, B) == 74
print('Su codigo paso todos los tests!')

Su codigo paso todos los tests!


# Parte 4

Pruebe cuánto tiempo demora cada una de las funciones implementados en calcular la distancia para series de valores. Para esto, el siguiente código mide el tiempo que demoran las tres funciones con series de valores $A$ y $B$ del mismo largo, con largo $n$ variando desde 1 hasta 10. Concluya sobre la eficiencia de las funciones implementadas a partir de los resultados obtenidos.

In [ ]:
for n in range(1,11):
    A = numpy.random.randint(1,10,n)
    B = numpy.random.randint(1,10,n)
    print(A, B)
    %timeit distanciaRecursiva(A,B)
    %timeit distanciaMemoizacion(A,B)
    %timeit distanciaProgramacionDinamica(A,B)

[6] [6]
2.33 µs ± 84.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
8.44 µs ± 169 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
7.21 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[9 6] [8 5]
17.5 µs ± 191 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
26.8 µs ± 894 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
21.9 µs ± 788 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[6 4 3] [4 6 2]
94.3 µs ± 1.95 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
59.2 µs ± 1.02 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
44.7 µs ± 799 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[6 4 3 1] [5 4 6 1]
508 µs ± 31.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
103 µs ± 3.02 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
76.3 µs ± 2.02 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[5 1 9 7 5] [3 4 2 8 2]
2.65 ms ± 63.6 µs per loop (mean ± st

Conclusión sobre los resultados experimentales:

Lo que podemos notar es que para matrices pequeñas de 1 o 2 valores, la distancia recursiva demoró menos que los otros dos métodos, pero a medida que las matrices aumentaban, la distancia recursiva era cada vez más lenta en procesar los datos, mientras que los de memoización y programación dinámica no tenían esa demora. Por lo que, para secuencias largas, será más conveniente utilizar programación dinámica.